DROP TABLE IF EXISTS RegisteredUsers

CREATE TABLE RegisteredUsers(
	Fname NVARCHAR(100) NOT NULL,
	Lname NVARCHAR(100) NOT NULL,
	UserName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
)